In [0]:
import tensorflow as tf
print(tf.__version__)
import matplotlib.pyplot as plt

2.2.0-rc4


In [0]:
import pandas as pd
import numpy as np

In [0]:
#Numpy array
A  = [1,3,4]


In [0]:
A

[1, 3, 4]

In [0]:
B = np.array(A)
B

array([1, 3, 4])

In [0]:
E = [[1,3,5] , [4,5,6] , [4,7,3]] 
E

[[1, 3, 5], [4, 5, 6], [4, 7, 3]]

In [0]:
F = np.array(E)
F

array([[1, 3, 5],
       [4, 5, 6],
       [4, 7, 3]])

In [0]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
df = pd.DataFrame({'x': x,'Sin x': np.sin(x), 'Cos x': np.cos(x)})
df

x     Sin x     Cos x
0   1.0  0.841471  0.540302
1   2.0  0.909297 -0.416147
2   3.0  0.141120 -0.989992
3   4.0 -0.756802 -0.653644
4   5.0 -0.958924  0.283662
5   6.0 -0.279415  0.960170
6   7.0  0.656987  0.753902
7   8.0  0.989358 -0.145500
8   9.0  0.412118 -0.911130
9  10.0 -0.544021 -0.839072

In [0]:
df2 = pd.DataFrame.from_records(E)
df2

0  1  2
0  1  3  5
1  4  5  6
2  4  7  3

In [0]:
import zipfile
path_to_zip_file = "/content/CrossValidateSet.zip"
directory_to_extract_to = "/content/"
with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
    zip_ref.extractall(directory_to_extract_to)

In [0]:
myCsv = pd.read_csv("/content/CrossValidateSet/1.txt", names=["Class", "X", "Y", "Width","Height"], header=None, delimiter = "\t")

In [0]:
pd.set_option("display.precision", 2)
print(myCsv)
print(type(myCsv))
print(len(myCsv))
print(myCsv.shape)

    Class     X     Y     Width    Height
0       0  0.63  0.51  2.64e-02  2.65e-02
1       0  0.46  0.78  2.79e-02  3.06e-02
2       0  0.18  0.53  3.41e-02  3.67e-02
3       0  0.37  0.23  1.86e-02  2.04e-02
4       0  0.67  0.19  2.02e-02  2.24e-02
5       1  0.52  0.19  1.16e-02  1.22e-02
6       1  0.55  0.24  6.98e-03  5.10e-03
7       1  0.55  0.23  7.75e-03  5.10e-03
8       1  0.54  0.22  6.98e-03  7.14e-03
9       1  0.54  0.21  5.43e-03  1.12e-02
10      1  0.54  0.20  3.88e-03  8.16e-03
11      1  0.53  0.19  6.20e-03  1.02e-02
12      1  0.56  0.18  6.20e-03  9.18e-03
13      1  0.57  0.17  7.75e-03  7.14e-03
14      1  0.56  0.16  8.53e-03  1.12e-02
15      1  0.56  0.15  4.65e-03  6.12e-03
16      1  0.56  0.14  5.43e-03  6.12e-03
17      1  0.57  0.14  6.20e-03  8.16e-03
18      1  0.57  0.13  6.98e-03  8.16e-03
19      1  0.51  0.12  4.65e-03  6.12e-03
20      1  0.51  0.11  5.43e-03  8.16e-03
21      1  0.51  0.12  5.43e-03  1.02e-02
22      1  0.51  0.10  5.43e-03  1

In [0]:
print(myCsv.head())
print(myCsv.tail())
print(myCsv.info())

   Class     X     Y  Width  Height
0      0  0.63  0.51   0.03    0.03
1      0  0.46  0.78   0.03    0.03
2      0  0.18  0.53   0.03    0.04
3      0  0.37  0.23   0.02    0.02
4      0  0.67  0.19   0.02    0.02
    Class     X     Y     Width    Height
26      1  0.48  0.13  5.43e-03  5.10e-03
27      1  0.55  0.09  6.20e-03  7.14e-03
28      1  0.54  0.09  8.53e-03  3.06e-03
29      1  0.56  0.19  6.20e-03  1.12e-02
30      2  0.52  0.02  2.48e-02  3.98e-02
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Class   31 non-null     int64  
 1   X       31 non-null     float64
 2   Y       31 non-null     float64
 3   Width   31 non-null     float64
 4   Height  31 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 1.3 KB
None


In [0]:
print(myCsv.describe())

print(myCsv["Width"].value_counts(3))


       Class      X      Y     Width    Height
count  31.00  31.00  31.00  3.10e+01  3.10e+01
mean    0.87   0.52   0.20  9.98e-03  1.19e-02
std     0.43   0.08   0.15  8.11e-03  9.53e-03
min     0.00   0.18   0.02  3.88e-03  3.06e-03
25%     1.00   0.51   0.12  5.43e-03  6.12e-03
50%     1.00   0.54   0.16  6.20e-03  8.16e-03
75%     1.00   0.56   0.21  8.53e-03  1.12e-02
max     2.00   0.67   0.78  3.41e-02  3.98e-02
5.43e-03    0.26
6.20e-03    0.16
4.65e-03    0.10
6.98e-03    0.10
8.53e-03    0.06
7.75e-03    0.06
3.88e-03    0.03
2.48e-02    0.03
2.02e-02    0.03
2.79e-02    0.03
1.16e-02    0.03
2.64e-02    0.03
3.41e-02    0.03
1.86e-02    0.03
Name: Width, dtype: float64
